server:
  port: 8081
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: #username
    password: #password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
kafka:
  bootstrap-address: localhost:9092
  group-id: notification-group
  topic:
    name: notifications